<?php
namespace Database\Seeders;
use App\Models\{CareerAspiration,Competency,Department,DevelopmentActivity,Employee,GapAnalysis,PerformanceReview,Position,SmartTarget,User}; use Illuminate\Database\Seeder; use Illuminate\Support\Facades\Hash;
class DatabaseSeeder extends Seeder { public function run():void {
 $hc=User::create(['name'=>'Nadia Putri','email'=>'hc@growpath.test','password'=>Hash::make('password'),'role'=>'hc']); $user=User::create(['name'=>'Aliyah Rahma','email'=>'aliyah@growpath.test','password'=>Hash::make('password'),'role'=>'employee']);
 $dept=Department::create(['name'=>'Human Capital']); $staff=Position::create(['name'=>'Staff Human Capital','department_id'=>$dept->id,'level'=>1]); $senior=Position::create(['name'=>'Senior Human Capital Staff','department_id'=>$dept->id,'level'=>2]); Position::create(['name'=>'Supervisor Human Capital','department_id'=>$dept->id,'level'=>3]); Position::create(['name'=>'Manager Human Capital','department_id'=>$dept->id,'level'=>4]);
 $competencies=collect(['Leadership','Communication','Problem Solving','Analytical Thinking','Collaboration'])->map(fn($name)=>Competency::create(['name'=>$name,'description'=>'Kompetensi inti untuk pengembangan karier.'])); foreach($competencies as $c){$staff->competencies()->attach($c->id,['required_level'=>2]);$senior->competencies()->attach($c->id,['required_level'=>in_array($c->name,['Leadership','Problem Solving'])?4:($c->name==='Communication'?4:3)]);}
 $employee=Employee::create(['user_id'=>$user->id,'employee_number'=>'EMP-2024-0142','department_id'=>$dept->id,'position_id'=>$staff->id,'manager_id'=>$hc->id,'joined_at'=>'2024-01-15']); CareerAspiration::create(['employee_id'=>$employee->id,'target_position_id'=>$senior->id,'target_date'=>'2027-01-01','reason'=>'Saya ingin memperkuat kepemimpinan dan kontribusi strategis pada fungsi Human Capital.']);
 $assessment=$employee->assessments()->create(['assessment_date'=>'2026-08-20','status'=>'submitted']); $levels=['Leadership'=>2,'Communication'=>4,'Problem Solving'=>2,'Analytical Thinking'=>3,'Collaboration'=>4]; foreach($competencies as $c){$current=$levels[$c->name];$required=$senior->competencies()->whereKey($c->id)->first()->pivot->required_level;$gap=max(0,$required-$current);$assessment->details()->create(['competency_id'=>$c->id,'level'=>$current]);GapAnalysis::create(['employee_id'=>$employee->id,'competency_id'=>$c->id,'current_level'=>$current,'required_level'=>$required,'gap'=>$gap,'priority'=>$gap>=2?'high':($gap?'medium':'none')]);}
 PerformanceReview::create(['employee_id'=>$employee->id,'reviewer_id'=>$hc->id,'period'=>'Jan — Jun 2026','overall_score'=>4.2,'target_achievement'=>4,'quality_of_work'=>4,'productivity'=>4,'collaboration'=>5,'strengths'=>'Communication, Collaboration','development_areas'=>'Leadership, Problem Solving','manager_feedback'=>'Aliyah menunjukkan kolaborasi yang sangat baik. Fokus pengembangan berikutnya adalah keberanian memimpin proyek lintas unit.','status'=>'published']);
  $leadership=$competencies->firstWhere('name','Leadership');$problem=$competencies->firstWhere('name','Problem Solving');$leadGap=$employee->gaps()->where('competency_id',$leadership->id)->first();$target=SmartTarget::create(['employee_id'=>$employee->id,'gap_analysis_id'=>$leadGap->id,'statement'=>'Dalam 6 bulan mampu memimpin minimal 1 project lintas unit dengan hasil evaluasi minimal 4/5.','start_date'=>'2026-07-01','due_date'=>'2026-12-31','status'=>'active']);
  DevelopmentActivity::insert([['employee_id'=>$employee->id,'smart_target_id'=>$target->id,'competency_id'=>$leadership->id,'category'=>'70% Experiential','activity_type'=>'Project','name'=>'Memimpin Project X','description'=>'Memimpin implementasi onboarding digital.','target_output'=>'Project selesai sesuai timeline','start_date'=>'2026-07-01','end_date'=>'2026-12-31','pic'=>'Nadia Putri','success_indicator'=>'Feedback minimal 4/5','activity_log'=>'Memimpin kick-off dan koordinasi implementasi onboarding digital.','insight'=>'Delegasi yang jelas mempercepat pengambilan keputusan.','progress'=>0,'status'=>'on_progress','created_at'=>now(),'updated_at'=>now()],['employee_id'=>$employee->id,'smart_target_id'=>$target->id,'competency_id'=>$leadership->id,'category'=>'20% Social','activity_type'=>'Mentoring','name'=>'Mentoring Leadership','description'=>'Sesi mentoring dengan Head of HC.','target_output'=>'4 sesi mentoring','start_date'=>'2026-07-15','end_date'=>'2026-11-15','pic'=>'Nadia Putri','success_indicator'=>'Reflection tiap sesi','activity_log'=>null,'insight'=>null,'progress'=>0,'status'=>'on_progress','created_at'=>now(),'updated_at'=>now()],['employee_id'=>$employee->id,'smart_target_id'=>$target->id,'competency_id'=>$problem->id,'category'=>'10% Formal','activity_type'=>'Training','name'=>'Leadership Development Training','description'=>'Pelatihan kepemimpinan dasar.','target_output'=>'Sertifikat kelulusan','start_date'=>'2026-06-01','end_date'=>'2026-06-30','pic'=>'Learning Team','success_indicator'=>'Nilai minimal 80','activity_log'=>null,'insight'=>null,'progress'=>0,'status'=>'on_progress','created_at'=>now(),'updated_at'=>now()]]);
}}
