<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::table('users', fn (Blueprint $t) => $t->string('role')->default('employee')->index());
        Schema::create('departments', function (Blueprint $t) { $t->id(); $t->string('name')->unique(); $t->timestamps(); });
        Schema::create('positions', function (Blueprint $t) { $t->id(); $t->string('name'); $t->foreignId('department_id')->nullable()->constrained()->nullOnDelete(); $t->unsignedInteger('level')->default(1); $t->timestamps(); });
        Schema::create('employees', function (Blueprint $t) { $t->id(); $t->foreignId('user_id')->unique()->constrained()->cascadeOnDelete(); $t->string('employee_number')->unique(); $t->foreignId('department_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('position_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('manager_id')->nullable()->constrained('users')->nullOnDelete(); $t->date('joined_at')->nullable(); $t->timestamps(); });
        Schema::create('competencies', function (Blueprint $t) { $t->id(); $t->string('name'); $t->text('description')->nullable(); $t->timestamps(); });
        Schema::create('position_competencies', function (Blueprint $t) { $t->id(); $t->foreignId('position_id')->constrained()->cascadeOnDelete(); $t->foreignId('competency_id')->constrained()->cascadeOnDelete(); $t->unsignedTinyInteger('required_level'); $t->unique(['position_id','competency_id']); });
        Schema::create('career_aspirations', function (Blueprint $t) { $t->id(); $t->foreignId('employee_id')->constrained()->cascadeOnDelete(); $t->foreignId('target_position_id')->constrained('positions'); $t->date('target_date'); $t->text('reason')->nullable(); $t->timestamps(); });
        Schema::create('performance_reviews', function (Blueprint $t) { $t->id(); $t->foreignId('employee_id')->constrained()->cascadeOnDelete(); $t->foreignId('reviewer_id')->nullable()->constrained('users')->nullOnDelete(); $t->string('period'); $t->decimal('overall_score',3,1)->nullable(); $t->unsignedTinyInteger('target_achievement')->nullable(); $t->unsignedTinyInteger('quality_of_work')->nullable(); $t->unsignedTinyInteger('productivity')->nullable(); $t->unsignedTinyInteger('collaboration')->nullable(); $t->text('strengths')->nullable(); $t->text('development_areas')->nullable(); $t->text('manager_feedback')->nullable(); $t->text('confidential_notes')->nullable(); $t->string('status')->default('draft'); $t->timestamps(); });
        Schema::create('self_assessments', function (Blueprint $t) { $t->id(); $t->foreignId('employee_id')->constrained()->cascadeOnDelete(); $t->date('assessment_date'); $t->string('status')->default('draft'); $t->timestamps(); });
        Schema::create('self_assessment_details', function (Blueprint $t) { $t->id(); $t->foreignId('self_assessment_id')->constrained()->cascadeOnDelete(); $t->foreignId('competency_id')->constrained()->cascadeOnDelete(); $t->unsignedTinyInteger('level'); $t->unique(['self_assessment_id','competency_id']); });
        Schema::create('gap_analyses', function (Blueprint $t) { $t->id(); $t->foreignId('employee_id')->constrained()->cascadeOnDelete(); $t->foreignId('competency_id')->constrained()->cascadeOnDelete(); $t->unsignedTinyInteger('current_level'); $t->unsignedTinyInteger('required_level'); $t->unsignedTinyInteger('gap'); $t->string('priority'); $t->timestamps(); });
        Schema::create('smart_targets', function (Blueprint $t) { $t->id(); $t->foreignId('employee_id')->constrained()->cascadeOnDelete(); $t->foreignId('gap_analysis_id')->constrained()->cascadeOnDelete(); $t->text('statement'); $t->date('start_date'); $t->date('due_date'); $t->string('status')->default('active'); $t->timestamps(); });
        Schema::create('development_activities', function (Blueprint $t) { $t->id(); $t->foreignId('employee_id')->constrained()->cascadeOnDelete(); $t->foreignId('smart_target_id')->nullable()->constrained()->nullOnDelete(); $t->foreignId('competency_id')->constrained()->cascadeOnDelete(); $t->string('category'); $t->string('activity_type'); $t->string('name'); $t->text('description')->nullable(); $t->string('target_output')->nullable(); $t->date('start_date'); $t->date('end_date'); $t->string('pic')->nullable(); $t->string('success_indicator')->nullable(); $t->text('activity_log')->nullable(); $t->text('insight')->nullable(); $t->string('evidence_path')->nullable(); $t->unsignedTinyInteger('progress')->default(0); $t->string('status')->default('not_started'); $t->timestamps(); });
    }
    public function down(): void { foreach (['development_activities','smart_targets','gap_analyses','self_assessment_details','self_assessments','performance_reviews','career_aspirations','position_competencies','competencies','employees','positions','departments'] as $table) Schema::dropIfExists($table); Schema::table('users', fn (Blueprint $t) => $t->dropColumn('role')); }
};
