<?php
namespace App\Http\Controllers;
use App\Models\{CareerAspiration,Competency,DevelopmentActivity,Employee,GapAnalysis,PerformanceReview,Position,SmartTarget}; use Illuminate\Http\Request; use Illuminate\Support\Facades\Auth; use Illuminate\Support\Facades\Storage;
class GrowPathController extends Controller {
 private function employee(): Employee { return Auth::user()->employee ?? abort(403,'Halaman ini khusus pegawai.'); } private function hc(): void { abort_unless(Auth::user()->role==='hc',403); }
 public function dashboard(){ if(Auth::user()->role==='hc')return redirect()->route('hc.dashboard'); $employee=$this->employee();$employee->load('position','department','careerAspiration.targetPosition');$gaps=$employee->missingAspirationCompetencies();$activities=$employee->activities()->with('competency')->latest()->get();$ongoingActivities=$activities->reject(fn($activity)=>$activity->status==='completed')->values();$activeTargetCount=$employee->targets()->where('status','active')->count();return view('employee.dashboard',compact('employee','gaps','activities','ongoingActivities','activeTargetCount')); }
 public function career(){ $employee=$this->employee();return view('employee.career',['employee'=>$employee->load('position','competencies'),'review'=>$employee->reviews()->where('status','published')->latest()->first()]); }
 public function saveCareer(Request $request){$employee=$this->employee();$data=$request->validate(['target_position_id'=>'required|exists:positions,id','reason'=>'nullable|string|max:1000']);CareerAspiration::updateOrCreate(['employee_id'=>$employee->id],$data);$this->calculateGaps($employee);return back()->with('success','Aspirasi karier tersimpan dan gap kompetensi diperbarui.');}
 public function competencies(){ $employee=$this->employee();$employee->load('careerAspiration.targetPosition','position');$positions=Position::with('competencies')->orderBy('level')->orderBy('name')->get();$recommendedPositions=$positions->where('department_id',$employee->department_id)->where('level','>',$employee->position?->level ?? 0);$otherPositions=$positions->filter(fn($position)=>$position->department_id!==$employee->department_id);return view('employee.competencies',['employee'=>$employee,'gaps'=>$employee->missingAspirationCompetencies(),'recommendedPositions'=>$recommendedPositions,'otherPositions'=>$otherPositions]); }
 public function plan(){ $employee=$this->employee();$recommendedGaps=$employee->gaps()->with('competency')->where('gap','>',0)->get();return view('employee.plan',['employee'=>$employee,'recommendedGaps'=>$recommendedGaps,'otherCompetencies'=>Competency::whereNotIn('id',$recommendedGaps->pluck('competency_id'))->orderBy('name')->get(),'targets'=>$employee->targets()->with('gap.competency','activities')->where('status','active')->latest()->get()]); }
 public function history(){ $employee=$this->employee();return view('employee.history',['targets'=>$employee->targets()->with('gap.competency','activities')->where('status','employee_declared')->latest()->get()]); }
 public function saveTarget(Request $request){$employee=$this->employee();$data=$request->validate(['competency_id'=>'required|exists:competencies,id','statement'=>'required|string|max:160']);$gap=$employee->gaps()->firstOrCreate(['competency_id'=>$data['competency_id']],['current_level'=>1,'required_level'=>1,'gap'=>0,'priority'=>'none']);$employee->targets()->create(['gap_analysis_id'=>$gap->id,'statement'=>$data['statement']]);return back()->with('success','Target ditambahkan.');}
 public function targetDetail(SmartTarget $target){$employee=$this->employee();abort_unless($target->employee_id===$employee->id,403);$target->load('gap.competency','activities.competency');$recommendedPrograms=\App\Models\DevelopmentProgram::with(['registrations'=>fn($query)=>$query->where('employee_id',$employee->id)->where('smart_target_id',$target->id)])->where('status','active')->whereIn('category',['20% Social','10% Formal'])->where('competency_id',$target->gap->competency_id)->latest()->get();$categories=['70% Experiential','20% Social','10% Formal'];$covered=$target->activities->pluck('category')->unique();$canComplete=$covered->intersect($categories)->count()===3 && $target->activities->isNotEmpty() && $target->activities->every(fn($activity)=>$activity->status==='completed');return view('employee.target-detail',compact('target','categories','covered','canComplete','recommendedPrograms'));}
 public function completeTarget(SmartTarget $target){$employee=$this->employee();abort_unless($target->employee_id===$employee->id,403);$categories=['70% Experiential','20% Social','10% Formal'];$activities=$target->activities;if($activities->isEmpty()||$activities->pluck('category')->intersect($categories)->unique()->count()!==3||$activities->contains(fn($a)=>$a->status!=='completed'))return back()->withErrors(['target'=>'Lengkapi minimal satu aktivitas yang selesai pada setiap kategori 70/20/10 sebelum menyelesaikan target.']);$target->update(['status'=>'employee_declared']);return back()->with('success','Target dideklarasikan tercapai dan siap ditinjau HC.');}
 public function activities(){ $employee=$this->employee();return view('employee.activities',['employee'=>$employee,'activities'=>$employee->activities()->with('competency','target.gap.competency')->latest()->get(),'targets'=>$employee->targets()->with('gap.competency')->where('status','active')->get()]); }
 public function saveActivity(Request $request){$employee=$this->employee();$data=$request->validate(['smart_target_id'=>'required|exists:smart_targets,id','name'=>'required|string|max:160','category'=>'required|in:70% Experiential,20% Social,10% Formal','activity_type'=>'required|string|max:100','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date']);$target=$employee->targets()->with('gap')->findOrFail($data['smart_target_id']);if($target->status!=='active')return back()->withErrors(['target'=>'Aktivitas tidak dapat ditambahkan ke target yang sudah selesai.']);$data['competency_id']=$target->gap->competency_id;$employee->activities()->create($data+['status'=>'not_started']);return redirect()->route('targets.show',$target)->with('success','Kegiatan ditambahkan ke target.');}
 public function activityDetail(DevelopmentActivity $activity){$employee=$this->employee();abort_unless($activity->employee_id===$employee->id,403);$activity->load('competency','target.gap.competency');$completionRequirements=[];if(blank($activity->activity_log))$completionRequirements[]='Kegiatan yang dilakukan belum diisi.';if(blank($activity->insight))$completionRequirements[]='Insight yang didapatkan belum diisi.';if(blank($activity->evidence_path))$completionRequirements[]='Foto dokumentasi belum diunggah.';if($activity->end_date->isFuture())$completionRequirements[]='Timeline belum selesai (berakhir '.$activity->end_date->format('d M Y').').';return view('employee.activity-detail',compact('activity','completionRequirements'));}
 public function showEvidence(DevelopmentActivity $activity){abort_unless($activity->employee_id===$this->employee()->id,403);abort_unless($activity->evidence_path&&Storage::disk('public')->exists($activity->evidence_path),404);return response()->file(Storage::disk('public')->path($activity->evidence_path));}
 public function updateActivity(Request $request,DevelopmentActivity $activity){abort_unless($activity->employee_id===$this->employee()->id,403);if($activity->status==='completed')return back()->withErrors(['activity'=>'Aktivitas yang sudah selesai tidak dapat diperbarui.']);$data=$request->validate(['activity_log'=>'nullable|string|max:2000','insight'=>'nullable|string|max:2000','evidence'=>'nullable|image|max:5120']);if($request->hasFile('evidence'))$data['evidence_path']=$request->file('evidence')->store('activity-evidences','public');unset($data['evidence']);$activity->update($data+['status'=>'on_progress']);return back()->with('success','Detail aktivitas diperbarui.');}
 public function updateActivityPlan(Request $request,DevelopmentActivity $activity){abort_unless($activity->employee_id===$this->employee()->id,403);if($activity->status==='completed')return back()->withErrors(['activity'=>'Rencana aktivitas yang sudah selesai tidak dapat diubah.']);$data=$request->validate(['name'=>'required|string|max:160','category'=>'required|in:70% Experiential,20% Social,10% Formal','activity_type'=>'required|string|max:100','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date']);$activity->update($data);return back()->with('success','Rencana aktivitas diperbarui.');}
 public function completeActivity(DevelopmentActivity $activity){abort_unless($activity->employee_id===$this->employee()->id,403);$missing=[];if(blank($activity->activity_log))$missing[]='kegiatan yang dilakukan';if(blank($activity->insight))$missing[]='insight';if(blank($activity->evidence_path))$missing[]='foto dokumentasi';if($activity->end_date->isFuture())$missing[]='timeline kegiatan belum selesai';if($missing)return back()->withErrors(['activity'=>'Aktivitas belum dapat diselesaikan: '.implode(', ',$missing).'.']);$activity->update(['status'=>'completed','progress'=>100]);return back()->with('success','Aktivitas selesai.');}
 public function progress(){ return redirect()->route('history'); }
 public function team(){ $reports=Auth::user()->managedEmployees()->with('user','position','department','reviews')->get();abort_unless($reports->isNotEmpty(),403);return view('manager.team',compact('reports')); }
 public function teamEmployee(Employee $employee){abort_unless($employee->manager_id===Auth::id(),403);$employee->load('user','position','department','competencies','careerAspiration.targetPosition','targets.gap.competency','targets.activities','reviews');$aspirationGaps=$employee->missingAspirationCompetencies();return view('manager.employee-detail',compact('employee','aspirationGaps'));}
 public function teamReview(Employee $employee){abort_unless($employee->manager_id===Auth::id(),403);return view('manager.review',compact('employee'));}
 public function saveTeamReview(Request $request,Employee $employee){abort_unless($employee->manager_id===Auth::id(),403);$data=$request->validate(['period'=>'required|string|max:100','overall_score'=>'required|numeric|min:1|max:5','target_achievement'=>'nullable|integer|min:1|max:5','quality_of_work'=>'nullable|integer|min:1|max:5','productivity'=>'nullable|integer|min:1|max:5','collaboration'=>'nullable|integer|min:1|max:5','strengths'=>'nullable|string|max:1000','development_areas'=>'nullable|string|max:1000','manager_feedback'=>'nullable|string|max:2000']);$employee->reviews()->create($data+['reviewer_id'=>Auth::id(),'status'=>'draft']);return redirect()->route('team')->with('success','Review dikirim ke HC untuk dipublikasikan.');}
 public function registerProgram(SmartTarget $target,\App\Models\DevelopmentProgram $program){$employee=$this->employee();abort_unless($target->employee_id===$employee->id,403);abort_unless($target->status==='active'&&$program->status==='active'&&in_array($program->category,['20% Social','10% Formal'])&&$program->competency_id===$target->gap->competency_id,403);\App\Models\ProgramRegistration::firstOrCreate(['development_program_id'=>$program->id,'employee_id'=>$employee->id,'smart_target_id'=>$target->id],['status'=>'pending']);return back()->with('success','Pendaftaran program dikirim dan menunggu persetujuan HC.');}
 public function hcPrograms(){ $this->hc();return view('hc.programs',['programs'=>\App\Models\DevelopmentProgram::with('competency')->latest()->get(),'competencies'=>Competency::orderBy('name')->get(),'registrations'=>\App\Models\ProgramRegistration::with('program.competency','employee.user','target')->where('status','pending')->latest()->get()]); }
 public function saveHcProgram(Request $request){$this->hc();$data=$request->validate(['name'=>'required|string|max:160','competency_id'=>'required|exists:competencies,id','category'=>'required|in:20% Social,10% Formal','activity_type'=>'required|string|max:100','description'=>'nullable|string|max:1000','start_date'=>'required|date','end_date'=>'required|date|after_or_equal:start_date']);\App\Models\DevelopmentProgram::create($data);return back()->with('success','Program pengembangan ditambahkan.');}
 public function reviewProgramRegistration(Request $request,\App\Models\ProgramRegistration $registration){$this->hc();$data=$request->validate(['decision'=>'required|in:approved,rejected']);if($registration->status!=='pending')return back()->withErrors(['registration'=>'Pendaftaran ini sudah ditinjau.']);if($data['decision']==='approved'){$program=$registration->program;DevelopmentActivity::create(['employee_id'=>$registration->employee_id,'smart_target_id'=>$registration->smart_target_id,'competency_id'=>$program->competency_id,'program_registration_id'=>$registration->id,'category'=>$program->category,'activity_type'=>$program->activity_type,'name'=>$program->name,'description'=>$program->description,'start_date'=>$program->start_date,'end_date'=>$program->end_date,'status'=>'not_started']);}$registration->update(['status'=>$data['decision'],'reviewer_id'=>Auth::id(),'reviewed_at'=>now()]);return back()->with('success',$data['decision']==='approved'?'Pendaftaran disetujui dan aktivitas ditambahkan ke target.':'Pendaftaran ditolak.');}
 public function hcDashboard(){ $this->hc();return view('hc.dashboard',['employees'=>Employee::with('user','position')->get(),'reviews'=>PerformanceReview::with('employee.user')->latest()->get(),'highGaps'=>GapAnalysis::with('employee.user','competency')->where('priority','high')->get()]);}
 public function reviews(){ $this->hc();return view('hc.reviews',['reviews'=>PerformanceReview::with('employee.user','employee.position')->latest()->get()]);} public function publishReview(PerformanceReview $review){$this->hc();$review->update(['status'=>'published']);return back()->with('success','Performance Review berhasil dipublikasikan.');}
 public function calculateGaps(Employee $employee):void{$employee->load('competencies','careerAspiration.targetPosition.competencies');$owned=$employee->competencies->pluck('id');$aspiration=$employee->careerAspiration?->targetPosition?->competencies->pluck('id')??collect();foreach($aspiration->diff($owned) as $competencyId){GapAnalysis::updateOrCreate(['employee_id'=>$employee->id,'competency_id'=>$competencyId],['current_level'=>0,'required_level'=>1,'gap'=>1,'priority'=>'aspirasi']);}}
}
